// /* tslint:disable */

// export const chartsRoutesData = {
//     // doughnut-chart
//     "doughnut-chart-explosion": { displayName: "Doughnut Chart Explosion", parentName: "Doughnut Chart" },
//     "doughnut-chart-overview": { displayName: "Doughnut Chart Overview", parentName: "Doughnut Chart" },
//     "doughnut-chart-selection": { displayName: "Doughnut Chart Selection", parentName: "Doughnut Chart" },
//     "doughnut-chart-legend": { displayName: "Doughnut Chart Legend", parentName: "Doughnut Chart" },
//     "doughnut-chart-rings": { displayName: "Doughnut Chart Rings", parentName: "Doughnut Chart" },
//     "doughnut-chart-animation": { displayName: "Doughnut Chart Animation", parentName: "Doughnut Chart" },

//     // pie-chart
//     "pie-chart-overview": { displayName: "Pie Chart Overview", parentName: "Pie Chart" },
//     "pie-chart-explosion": { displayName: "Pie Chart Explosion", parentName: "Pie Chart" },
//     "pie-chart-legend": { displayName: "Pie Chart Legend", parentName: "Pie Chart" },
//     "pie-chart-others": { displayName: "Pie Chart Others Slice", parentName: "Pie Chart" },
//     "pie-chart-selection": { displayName: "Pie Chart Selection", parentName: "Pie Chart" },
//     "pie-chart-animation": { displayName: "Pie Chart Animation", parentName: "Pie Chart" },
//     "pie-chart-styling": { displayName: "Pie Chart Styling", parentName: "Pie Chart" },

//     // category-chart
//     "category-chart-overview": { displayName: "Category Chart Overview", parentName: "Category Chart" },
//     "category-chart-annotations": { displayName: "Category Chart Annotations", parentName: "Category Chart" },
//     "category-chart-overlap-columns": { displayName: "Category Chart Overlap Columns", parentName: "Category Chart" },
//     "category-chart-highlighting": { displayName: "Category Chart Highlighting", parentName: "Category Chart" },
//     "category-chart-high-volume": { displayName: "Category Chart High Volume", parentName: "Category Chart" },
//     "category-chart-high-frequency": { displayName: "Category Chart High Frequency", parentName: "Category Chart" },
//     "category-chart-axis-options": { displayName: "Category Chart Axis Options", parentName: "Category Chart" },
//     "category-chart-marker-options": { displayName: "Category Chart Marker Options", parentName: "Category Chart" },
//     "category-chart-marker-templates": { displayName: "Category Chart Marker Templates", parentName: "Category Chart" },
//     "category-chart-tooltip-template": { displayName: "Category Chart Tooltips Template", parentName: "Category Chart" },
//     "category-chart-tooltip-types": { displayName: "Category Chart Tooltip Types", parentName: "Category Chart" },
//     "category-chart-trendline": { displayName: "Category Chart Trendline", parentName: "Category Chart" },
//     "category-chart-axis-gap": { displayName: "Axis Gap", parentName: "Category Chart" },
//     "category-chart-axis-gridlines": { displayName: "Axis Gridlines", parentName: "Category Chart" },
//     "category-chart-axis-labels": { displayName: "Axis Labels", parentName: "Category Chart" },
//     "category-chart-axis-locations": { displayName: "Axis Locations", parentName: "Category Chart" },
//     "category-chart-axis-overlap": { displayName: "Axis Overlap", parentName: "Category Chart" },
//     "category-chart-axis-range": { displayName: "Axis Range", parentName: "Category Chart" },
//     "category-chart-axis-tickmarks": { displayName: "Axis Tickmarks", parentName: "Category Chart" },
//     "category-chart-axis-titles": { displayName: "Axis Titles", parentName: "Category Chart" },

//     "category-chart-area-chart-multiple-sources": { displayName: "Area Chart Multiple Sources", parentName: "Category Chart"},
//     "category-chart-area-chart-single-source": { displayName: "Area Chart Single Source", parentName: "Category Chart"},
//     "category-chart-area-chart-styling": { displayName: "Area Chart Styling", parentName: "Category Chart"},

//     "category-chart-column-chart-multiple-sources": { displayName: "Column Chart Multiple Sources", parentName: "Category Chart"},
//     "category-chart-column-chart-single-source": { displayName: "Column Chart Single Source", parentName: "Category Chart"},
//     "category-chart-column-chart-with-highlighting": { displayName: "Column Chart With Highlighting", parentName: "Category Chart"},
//     "category-chart-column-chart-styling": { displayName: "Column Chart Styling", parentName: "Category Chart"},
//     "category-chart-column-chart-with-tooltips": { displayName: "Column Chart With Tooltips", parentName: "Category Chart"},

//     "category-chart-line-chart-multiple-sources": { displayName: "Line Chart Multiple Sources", parentName: "Category Chart" },
//     "category-chart-line-chart-single-source": { displayName: "Line Chart Single Source", parentName: "Category Chart" },
//     "category-chart-line-chart-styling": { displayName: "Line Chart Styling", parentName: "Category Chart" },
//     "category-chart-line-chart-with-annotations": { displayName: "Line Chart With Annotations", parentName: "Category Chart" },
//     "category-chart-line-chart-with-animations": { displayName: "Line Chart With Animations", parentName: "Category Chart" },
//     "category-chart-line-chart-with-titles": { displayName: "Line Chart With Titles", parentName: "Category Chart" },

//     "category-chart-point-chart-multiple-sources": { displayName: "Point Chart Multiple Sources", parentName: "Category Chart" },
//     "category-chart-point-chart-single-source": { displayName: "Point Chart Single Source", parentName: "Category Chart" },
//     "category-chart-point-chart-styling": { displayName: "Point Chart Styling", parentName: "Category Chart" },

//     "category-chart-spline-area-multiple-sources": { displayName: "Spline Area Multiple Sources", parentName: "Category Chart" },
//     "category-chart-spline-area-single-source": { displayName: "Spline Area Single Source", parentName: "Category Chart" },
//     "category-chart-spline-area-styling": { displayName: "Spline Area Styling", parentName: "Category Chart" },

//     "category-chart-spline-styling": { displayName: "Spline Styling", parentName: "Category Chart" },
//     "category-chart-spline-single-source": { displayName: "Spline Single Source", parentName: "Category Chart" },
//     "category-chart-spline-multiple-sources": { displayName: "Spline Multiple Sources", parentName: "Category Chart" },

//     "category-chart-step-area-multiple-sources": { displayName: "Step Area Multiple Sources", parentName: "Category Chart" },
//     "category-chart-step-area-single-source": { displayName: "Step Area Single Source", parentName: "Category Chart" },
//     "category-chart-step-area-styling": { displayName: "Step Area Styling", parentName: "Category Chart" },

//     "category-chart-step-line-multiple-sources": { displayName: "Step Line Multiple Sources", parentName: "Category Chart" },
//     "category-chart-step-line-single-source": { displayName: "Step Line Single Source", parentName: "Category Chart" },
//     "category-chart-step-line-styling": { displayName: "Step Line Styling", parentName: "Category Chart" },

//     // financial-chart
//     "financial-chart-overview": { displayName: "Financial Chart Overview", parentName: "Financial Chart" },
//     "financial-chart-performance": { displayName: "Financial Chart Performance", parentName: "Financial Chart" },
//     "financial-chart-annotations": { displayName: "Financial Chart Annotations", parentName: "Financial Chart" },
//     "financial-chart-titles": { displayName: "Financial Chart Titles", parentName: "Financial Chart" },
//     "financial-chart-panes": { displayName: "Financial Chart Panes", parentName: "Financial Chart" },
//     "financial-chart-multiple-data": { displayName: "Financial Chart Multiple Sources", parentName: "Financial Chart" },
//     "financial-chart-multiple-feeds": { displayName: "Financial Chart Multiple Feeds", parentName: "Financial Chart" },
//     "financial-chart-indicator-types": { displayName: "Financial Chart Indicator Types", parentName: "Financial Chart" },
//     "financial-chart-volume-type": { displayName: "Financial Chart Volume Types", parentName: "Financial Chart" },
//     "financial-chart-custom-indicators": { displayName: "Financial Chart Custom Indicators", parentName: "Financial Chart" },
//     "financial-chart-high-volume": { displayName: "Financial Chart High Volume", parentName: "Financial Chart" },
//     "financial-chart-high-frequency": { displayName: "Financial Chart High Frequency", parentName: "Financial Chart" },
//     "financial-chart-axis-types": { displayName: "Financial Chart Axis Types", parentName: "Financial Chart" },
//     "financial-chart-tooltip-template": { displayName: "Financial Chart Tooltips Template", parentName: "Financial Chart" },
//     "financial-chart-tooltip-types": { displayName: "Financial Chart Tooltip Types", parentName: "Financial Chart" },
//     "financial-chart-time-based-data": { displayName: "Financial Chart Time Based Data", parentName: "Financial Chart" },
//     "financial-chart-trendlines": { displayName: "Financial Chart Trendlines", parentName: "Financial Chart" },
//     "financial-chart-styling": { displayName: "Financial Chart Styling", parentName: "Financial Chart" },
//     "financial-chart-stock-index-chart": { displayName: "Financial Chart Stock Index Chart", parentName: "Financial Chart" },
//     // data-chart
//     // NOTE uncomment when implemented
//     // "data-chart-axis-locations": { displayName: "Data Chart Axis Locations", parentName: "Data Chart" },
//     "data-chart-axis-annotations": { displayName: "Data Chart Axis Annotations", parentName: "Data Chart" },
//     "data-chart-axis-settings": { displayName: "Data Chart Axis Settings", parentName: "Data Chart" },
//     "data-chart-axis-sharing": { displayName: "Data Chart Axis Sharing", parentName: "Data Chart" },
//     "data-chart-axis-types": { displayName: "Data Chart Axis Types", parentName: "Data Chart" },
//     "data-chart-legends": { displayName: "Data Chart Legends", parentName: "Data Chart" },
//     "data-chart-chart-navigation": { displayName: "Data Chart Navigation", parentName: "Data Chart" },
//     "data-chart-chart-overview": { displayName: "Data Chart Overview", parentName: "Data Chart" },
//     "data-chart-chart-synchronization": { displayName: "Data Chart Synchronization", parentName: "Data Chart" },
//     "data-chart-chart-titles": { displayName: "Data Chart Titles", parentName: "Data Chart" },
//     // NOTE uncomment when implemented
//     // "data-chart-chart-performance": { displayName: "Data Chart Performance", parentName: "Data Chart" },
//     // "data-chart-series-animations": { displayName: "Data Chart Series Animations", parentName: "Data Chart" },
//     "data-chart-series-annotations": { displayName: "Data Chart Series Annotations", parentName: "Data Chart" },
//     "data-chart-series-highlighting": { displayName: "Data Chart Series Highlighting", parentName: "Data Chart" },
//     "data-chart-series-markers": { displayName: "Data Chart Series Markers", parentName: "Data Chart" },
//     "data-chart-series-marker-template": { displayName: "Data Chart Series Marker Template", parentName: "Data Chart" },
//     "data-chart-series-tooltips": { displayName: "Data Chart Series Tooltips", parentName: "Data Chart" },
//     "data-chart-series-trendlines": { displayName: "Data Chart Series Trendlines", parentName: "Data Chart" },
//     "data-chart-type-category-series": { displayName: "Category Series", parentName: "Data Chart" },
//     "data-chart-type-category-area-series": { displayName: "Category Area Series", parentName: "Data Chart" },
//     "data-chart-type-category-bar-series": { displayName: "Category Bar Series", parentName: "Data Chart" },
//     "data-chart-type-category-column-series": { displayName: "Category Column Series", parentName: "Data Chart" },
//     "data-chart-type-category-line-series": { displayName: "Category Line Series", parentName: "Data Chart" },
//     "data-chart-type-category-point-series": { displayName: "Category Point Series", parentName: "Data Chart" },
//     "data-chart-type-category-spline-area-series": { displayName: "Category Spline Area Series", parentName: "Data Chart" },
//     "data-chart-type-category-spline-series": { displayName: "Category Spline Series", parentName: "Data Chart" },
//     "data-chart-type-category-step-area-series": { displayName: "Category Step Area Series", parentName: "Data Chart" },
//     "data-chart-type-category-step-line-series": { displayName: "Category Step Line Series", parentName: "Data Chart" },
//     "data-chart-type-category-waterfall-series": { displayName: "Category Waterfall Series", parentName: "Data Chart" },
//     "data-chart-type-financial-series": { displayName: "Financial Series Types", parentName: "Data Chart" },
//     "data-chart-type-financial-area-indicators": { displayName: "Financial Area Indicators", parentName: "Data Chart"},
//     "data-chart-type-financial-candlestick-series": { displayName: "Financial Candlestick Series", parentName: "Data Chart" },
//     "data-chart-type-financial-column-indicators": { displayName: "Financial Column Indicators", parentName: "Data Chart"},
//     "data-chart-type-financial-line-indicators": { displayName: "Financial Line Indicators", parentName: "Data Chart"},
//     "data-chart-type-financial-ohlc-series": { displayName: "Financial OHLC Series", parentName: "Data Chart" },
//     "data-chart-type-financial-overlays": { displayName: "Financial Overlays", parentName: "Data Chart"},
//     "data-chart-polar-chart-types": { displayName: "Polar Series", parentName: "Data Chart" },
//     // "data-chart-type-polar-area-series": { displayName: "Polar Area Series", parentName: "Data Chart" },
//     // "data-chart-type-polar-line-series": { displayName: "Polar Line Series", parentName: "Data Chart" },
//     // "data-chart-type-polar-scatter-series": { displayName: "Polar Scatter Series", parentName: "Data Chart" },
//     // "data-chart-type-polar-spline-area-series": { displayName: "Polar Spline Area Series", parentName: "Data Chart" },
//     // "data-chart-type-polar-spline-series": { displayName: "Polar Spline Series", parentName: "Data Chart" },
//     "data-chart-radial-chart-types": { displayName: "Radial Series", parentName: "Data Chart" },
//     "data-chart-type-radial-area-series": { displayName: "Radial Area Series", parentName: "Data Chart" },
//     "data-chart-type-radial-column-series": { displayName: "Radial Column Series", parentName: "Data Chart" },
//     "data-chart-type-radial-line-series": { displayName: "Radial Line Series", parentName: "Data Chart" },
//     "data-chart-type-radial-pie-series": { displayName: "Radial Pie Series", parentName: "Data Chart" },
//     "data-chart-type-range-series": { displayName: "Range Series", parentName: "Data Chart" },
//     "data-chart-type-range-area-series": { displayName: "Range Area Series", parentName: "Data Chart" },
//     "data-chart-type-range-column-series": { displayName: "Range Column Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-area-series":      { displayName: "Scatter Area Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-contour-series":   { displayName: "Scatter Contour Series", parentName: "Data Chart" },
//     // NOTE uncomment when implemented
//     "data-chart-type-scatter-hd-series":        { displayName: "Scatter HD Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-bubble-series":    { displayName: "Scatter Bubble Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-line-series":      { displayName: "Scatter Line Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-point-series":     { displayName: "Scatter Point Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-series":           { displayName: "Scatter Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-spline-series":    { displayName: "Scatter Spline Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-polygon-series":   { displayName: "Scatter Polygon Series", parentName: "Data Chart" },
//     "data-chart-type-scatter-polyline-series":  { displayName: "Scatter Polyline Series", parentName: "Data Chart" },
//     "data-chart-type-shape-series":             { displayName: "Scatter Shape Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-100-area-series":          { displayName: "Stacked 100 Area Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-100-bar-series":           { displayName: "Stacked 100 Bar Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-100-column-series":        { displayName: "Stacked 100 Column Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-100-line-series":          { displayName: "Stacked 100 Line Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-100-spline-series":        { displayName: "Stacked 100 Spline Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-100-spline-area-series":   { displayName: "Stacked 100 Spline Area Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-area-series":              { displayName: "Stacked Area Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-bar-series":               { displayName: "Stacked Bar Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-column-series":            { displayName: "Stacked Column Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-line-series":              { displayName: "Stacked Line Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-spline-series":            { displayName: "Stacked Spline Series", parentName: "Data Chart" },
//     "data-chart-type-stacked-spline-area-series":       { displayName: "Stacked Spline Area Series", parentName: "Data Chart" },
//     "data-chart-series-value-overlay":                  { displayName: "Data Chart Value Overlay", parentName: "Data Chart" },

//     // SEO samples
//     "data-chart-axis-crossing":                         { displayName: "Axis Crossing", parentName: "Data Chart" },
//     "data-chart-bar-chart-single-source":               { displayName: "Bar Chart Single Source", parentName: "Data Chart" },
//     "data-chart-bar-chart-multiple-sources":            { displayName: "Bar Chart Multiple Sources", parentName: "Data Chart" },
//     "data-chart-bar-chart-styling":                     { displayName: "Bar Chart Styling", parentName: "Data Chart" },
//     "data-chart-callout-layer-styling":                 { displayName: "Callout Layer Styling", parentName: "Data Chart"},
//     "data-chart-column-chart-styling":                  { displayName: "Column Chart Styling", parentName: "Data Chart"},
//     "data-chart-composite-chart":                       { displayName: "Composite Chart", parentName: "Data Chart"},
//     "data-chart-crosshair-layer-styling":               { displayName: "Crosshair Layer Styling", parentName: "Data Chart"},
//     "data-chart-final-value-layer-styling":             { displayName: "Final Value Layer Styling", parentName: "Data Chart"},
//     "data-chart-polar-area-chart":                      { displayName: "Polar Area Chart", parentName: "Data Chart" },
//     "data-chart-polar-area-chart-styling":              { displayName: "Polar Area Chart Styling", parentName: "Data Chart" },
//     "data-chart-polar-spline-area-chart":               { displayName: "Polar Spline Area Chart", parentName: "Data Chart" },
//     "data-chart-polar-line-chart":                      { displayName: "Polar Line Series", parentName: "Data Chart" },
//     "data-chart-polar-scatter-chart":                   { displayName: "Polar Scatter Series", parentName: "Data Chart" },
//     "data-chart-polar-spline-chart":                    { displayName: "Polar Spline Series", parentName: "Data Chart" },
//     "data-chart-radial-area-chart":                     { displayName: "Radial Area Chart", parentName: "Data Chart" },
//     "data-chart-radial-area-chart-styling":             { displayName: "Radial Area Chart Styling", parentName: "Data Chart" },
//     "data-chart-radial-column-chart":                   { displayName: "Radial Column Chart", parentName: "Data Chart" },
//     "data-chart-radial-line-chart":                     { displayName: "Radial Line Chart", parentName: "Data Chart" },
//     "data-chart-radial-pie-chart":                      { displayName: "Radial Pie Chart", parentName: "Data Chart" },
//     "data-chart-range-area-chart":                      { displayName: "Range Area Chart", parentName: "Data Chart" },
//     "data-chart-range-column-chart":                    { displayName: "Range Column Chart", parentName: "Data Chart" },
//     "data-chart-scatter-bubble-chart-multiple-sources": { displayName: "Scatter Bubble Chart Multiple Sources", parentName: "Data Chart" },
//     "data-chart-scatter-bubble-chart-single-source":    { displayName: "Scatter Bubble Chart Single Source", parentName: "Data Chart" },
//     "data-chart-scatter-bubble-chart-styling":          { displayName: "Scatter Bubble Chart Styling", parentName: "Data Chart" },
//     "data-chart-scatter-line-chart":                    { displayName: "Scatter Line Chart", parentName: "Data Chart" },
//     "data-chart-scatter-point-chart":                   { displayName: "Scatter Point Chart", parentName: "Data Chart" },
//     "data-chart-scatter-spline-chart":                  { displayName: "Scatter Spline Chart", parentName: "Data Chart" },
//     "data-chart-stacked-chart-types":                        { displayName: "Stacked Series", parentName: "Data Chart" },
//     "data-chart-stacked-100-area-chart":                { displayName: "Stacked 100 Area Chart", parentName: "Data Chart" },
//     "data-chart-stacked-100-bar-chart":                 { displayName: "Stacked 100 Bar Chart", parentName: "Data Chart" },
//     "data-chart-stacked-100-column-chart":              { displayName: "Stacked 100 Column Chart", parentName: "Data Chart" },
//     "data-chart-stacked-100-line-chart":                { displayName: "Stacked 100 Line Chart", parentName: "Data Chart" },
//     "data-chart-stacked-100-spline-chart":              { displayName: "Stacked 100 Spline Chart", parentName: "Data Chart" },
//     "data-chart-stacked-100-spline-area-chart":         { displayName: "Stacked 100 Spline Area Chart", parentName: "Data Chart" },
//     "data-chart-stacked-area-chart":                    { displayName: "Stacked Area Chart", parentName: "Data Chart" },
//     "data-chart-stacked-bar-chart":                     { displayName: "Stacked Bar Chart", parentName: "Data Chart" },
//     "data-chart-stacked-column-chart":                  { displayName: "Stacked Column Chart", parentName: "Data Chart" },
//     "data-chart-stacked-line-chart":                    { displayName: "Stacked Line Chart", parentName: "Data Chart" },
//     "data-chart-stacked-spline-chart":                  { displayName: "Stacked Spline Chart", parentName: "Data Chart" },
//     "data-chart-stacked-spline-area-chart":             { displayName: "Stacked Spline Area Chart", parentName: "Data Chart" },
//     "data-chart-waterfall-chart":                       { displayName: "Waterfall Chart", parentName: "Data Chart" },
//     "data-chart-tooltip-template":                      { displayName: "Tooltip Template", parentName: "Data Chart" },

//     // sparkline-chart
//     "sparkline-display-types":  { displayName: "Sparkline Display Types", parentName: "Sparkline"},
//     "sparkline-grid":           { displayName: "Sparkline Grid", parentName: "Sparkline"},
//     "sparkline-markers":        { displayName: "Sparkline Markers", parentName: "Sparkline"},
//     "sparkline-normal-range":   { displayName: "Sparkline Normal Range", parentName: "Sparkline"},
//     "sparkline-trendlines":     { displayName: "Sparkline Trendlines", parentName: "Sparkline"},
//     "sparkline-unknown-values": { displayName: "Sparkline Unknown Values", parentName: "Sparkline"},
//     // zoomslider-chart
//     "zoomslider-overview": { displayName: "Zoom Slider Overview", parentName: "Zoom Slider"},
//      // tree-map-chart
//      "tree-map-events":   { displayName: "Tree Map Events", parentName: "Tree Map"},
//      "tree-map-layout":   { displayName: "Tree Map Layout", parentName: "Tree Map"},
//      "tree-map-overview": { displayName: "Tree Map Overview", parentName: "Tree Map"},
//      "tree-map-styling":  { displayName: "Tree Map Styling", parentName: "Tree Map"}
// };
