trigger:
  branches:
    include:
    - 'vnext'
    - 'btraykov-azure-pipeline'

# This pipeline is meant to run on changes pushed to the vnext branch only.
# If it runs on PRs, it will create PRs to the destination repos' vnext branches - we don't want that.
pr: none

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

# TODO: Remove this section this out as soon as the state of the vnext branch is good enough
resources:
  repositories:
    - repository: selfi
      endpoint: 'ESShared'
      type: github
      ref: eebcb2a # last known ref where the npm build is successful - need it to verify the newly-developed release process
      name: igniteui-angular-examples
  

pool:
  name: BuildAgentOnPrem

jobs:
- job:
  displayName: Build
  workspace:
    clean: resources
  steps:
  - checkout: self
    enabled: false
    clean: true
    path: igniteui-angular-examples # this is explicitly required by the samples browser build process

  - checkout: selfi
    enabled: true
    clean: true
    path: igniteui-angular-examples # this is explicitly required by the samples browser build process

  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)\browser'

  - task: PowerShell@2
    displayName: 'Apply very special configuration'
    inputs:
      targetType: 'inline'
      script: |
        Write-Output $pwd
        
        ((Get-Content -Path package.json -Raw) -replace 'build --configuration production','build --configuration production --base-href=/angular-demos-dv/') | Set-Content -Path package.json
      workingDirectory: '$(Build.SourcesDirectory)\browser'

  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)\browser'
      customCommand: 'run build'

    # TODO get steps from TFS pipeline. We need to do an npm install for sure
    # explicitly install npx (global?) and igniteui-cli - latest versionS 
    # use npx to call igniteui-cli to apply the Angular schematic (trial -> licensed)
    # follow steps & pray to Jesus

    # 1. npm install
    # 2. gulp updateBrowser
    # 3. Copy-Item "$rootpath\@infragistics\*" -Destination "$rootpath" -Recurse # Move @infragistics\* folders up
    # 4. ((Get-Content -Path package.json -Raw) -replace 'build --configuration production','build --configuration production --base-href=/angular-demos-dv/') | Set-Content -Path package.json
    # 5. npm run build

    # TODO Convert Octopus Deploy deployment to Azure release pipeline & pray to Jesus

    #